# Generated by Django 5.1.3 on 2025-11-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_materialcompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='resource_url',
        ),
        migrations.AddField(
            model_name='material',
            name='media_file',
            field=models.FileField(blank=True, help_text='Upload videos, PDFs, images, or other assets that play inline.', null=True, upload_to='materials/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, help_text='Body text, transcript, or instructions written by administrators.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_protected',
            field=models.BooleanField(default=True, help_text='Controls UI hints that discourage downloads/copying.'),
        ),
    ]
