# Generated by Django 5.1.3 on 2025-12-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_material_resource_url_material_media_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_payload', models.JSONField(help_text='Student answer data: single choice (string), multiple choice (array), free response (text).')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('graded', 'Graded')], default='pending', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score percentage (0-100).', max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Instructor feedback for the submission.')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Attempt number')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(limit_choices_to={'material_type': 'task'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.material', verbose_name='Material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'task submission',
                'verbose_name_plural': 'task submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['material', 'student', '-submitted_at'], name='courses_tas_materia_fa6c34_idx')],
            },
        ),
    ]
